version: "3"
services:
  node_backend:
    container_name: "server"
    build: ./server/
    ports:
      - "3001:3001"
  pg:
    image: "postgres:13"
    container_name: "postgres"
    ports:
      - "3002:3002"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=summer_db
    volumes:
      - ./pg/db_data:/var/lib/postgresql/data
  react_frontend:
    container_name: "client"
    build: ./client/
    ports:
      - "3000:3000"
